version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - "80:80"
        links:
            -   fpm
        volumes:
            - ./:/var/www/adminpanel
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            -   ./:/var/www/adminpanel
        links:
            -   mysql
    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            -     mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
